# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from external_server.models.base_model_ import Model
from external_server.models.model_structure_inputs_inner import ModelStructureInputsInner
from external_server import util

from external_server.models.model_structure_inputs_inner import ModelStructureInputsInner  # noqa: E501


class ModelStructure(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, inputs=None, outputs=None):  # noqa: E501
        """ModelStructure - a model defined in OpenAPI

        :param inputs: The inputs of this ModelStructure.  # noqa: E501
        :type inputs: List[ModelStructureInputsInner]
        :param outputs: The outputs of this ModelStructure.  # noqa: E501
        :type outputs: List[ModelStructureInputsInner]
        """
        self.openapi_types = {"inputs": List[ModelStructureInputsInner], "outputs": List[ModelStructureInputsInner]}

        self.attribute_map = {"inputs": "inputs", "outputs": "outputs"}

        self._inputs = inputs
        self._outputs = outputs

    @classmethod
    def from_dict(cls, dikt) -> "ModelStructure":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelStructure of this ModelStructure.  # noqa: E501
        :rtype: ModelStructure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inputs(self):
        """Gets the inputs of this ModelStructure.


        :return: The inputs of this ModelStructure.
        :rtype: List[ModelStructureInputsInner]
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this ModelStructure.


        :param inputs: The inputs of this ModelStructure.
        :type inputs: List[ModelStructureInputsInner]
        """

        self._inputs = inputs

    @property
    def outputs(self):
        """Gets the outputs of this ModelStructure.


        :return: The outputs of this ModelStructure.
        :rtype: List[ModelStructureInputsInner]
        """
        return self._outputs

    @outputs.setter
    def outputs(self, outputs):
        """Sets the outputs of this ModelStructure.


        :param outputs: The outputs of this ModelStructure.
        :type outputs: List[ModelStructureInputsInner]
        """

        self._outputs = outputs
