# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from external_server.models.base_model_ import Model
from external_server import util


class ModelInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item_count=None):  # noqa: E501
        """ModelInput - a model defined in OpenAPI

        :param item_count: The item_count of this ModelInput.  # noqa: E501
        :type item_count: int
        """
        self.openapi_types = {"item_count": int}

        self.attribute_map = {"item_count": "item_count"}

        self._item_count = item_count

    @classmethod
    def from_dict(cls, dikt) -> "ModelInput":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelInput of this ModelInput.  # noqa: E501
        :rtype: ModelInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_count(self):
        """Gets the item_count of this ModelInput.


        :return: The item_count of this ModelInput.
        :rtype: int
        """
        return self._item_count

    @item_count.setter
    def item_count(self, item_count):
        """Sets the item_count of this ModelInput.


        :param item_count: The item_count of this ModelInput.
        :type item_count: int
        """

        self._item_count = item_count
