# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from external_server.models.base_model_ import Model
from external_server import util


class ModelOutput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, score=None):  # noqa: E501
        """ModelOutput - a model defined in OpenAPI

        :param score: The score of this ModelOutput.  # noqa: E501
        :type score: float
        """
        self.openapi_types = {"score": float}

        self.attribute_map = {"score": "score"}

        self._score = score

    @classmethod
    def from_dict(cls, dikt) -> "ModelOutput":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelOutput of this ModelOutput.  # noqa: E501
        :rtype: ModelOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def score(self):
        """Gets the score of this ModelOutput.


        :return: The score of this ModelOutput.
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this ModelOutput.


        :param score: The score of this ModelOutput.
        :type score: float
        """

        self._score = score
