# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from external_server.models.base_model_ import Model
from external_server import util


class ModelStructureInputsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, shape=None):  # noqa: E501
        """ModelStructureInputsInner - a model defined in OpenAPI

        :param name: The name of this ModelStructureInputsInner.  # noqa: E501
        :type name: str
        :param shape: The shape of this ModelStructureInputsInner.  # noqa: E501
        :type shape: List[str]
        """
        self.openapi_types = {"name": str, "shape": List[str]}

        self.attribute_map = {"name": "name", "shape": "shape"}

        self._name = name
        self._shape = shape

    @classmethod
    def from_dict(cls, dikt) -> "ModelStructureInputsInner":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelStructure_inputs_inner of this ModelStructureInputsInner.  # noqa: E501
        :rtype: ModelStructureInputsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ModelStructureInputsInner.


        :return: The name of this ModelStructureInputsInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelStructureInputsInner.


        :param name: The name of this ModelStructureInputsInner.
        :type name: str
        """

        self._name = name

    @property
    def shape(self):
        """Gets the shape of this ModelStructureInputsInner.


        :return: The shape of this ModelStructureInputsInner.
        :rtype: List[str]
        """
        return self._shape

    @shape.setter
    def shape(self, shape):
        """Sets the shape of this ModelStructureInputsInner.


        :param shape: The shape of this ModelStructureInputsInner.
        :type shape: List[str]
        """

        self._shape = shape
