# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from external_server.models.base_model_ import Model
from external_server import util


class PredictRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """PredictRequest - a model defined in OpenAPI

        :param data: The data of this PredictRequest.  # noqa: E501
        :type data: file
        """
        self.openapi_types = {"data": file}

        self.attribute_map = {"data": "data"}

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> "PredictRequest":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The predict_request of this PredictRequest.  # noqa: E501
        :rtype: PredictRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this PredictRequest.


        :return: The data of this PredictRequest.
        :rtype: file
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this PredictRequest.


        :param data: The data of this PredictRequest.
        :type data: file
        """

        self._data = data
